### ISSUE TITLE
 The client library configuration is missing the required "use_proto_plus" key

### ISSUE THREAD

**Issue by BrianM3** [google/customer-match-upload-script#1]
I am running Python on windows. So I used pip install google-ads to install the google-ads library. But when I run the  create_and_populate_list.py I get the following error:

The client library configuration is missing the required "use_proto_plus" key

So I then copied the file from google-ads.yaml and updated the required parameters. event the client_id, client_secret and refresh_token although these parameters also exist in googleads_config.yaml file. I the edited the create_andpopulate_list.py and added 

client = GoogleAdsClient.load_from_storage("location of google-ads.yaml file")

but I still get the same error.

I then added the use_proto_plus: flag in the googleads_config.yaml. Still the same error.

Where must I put the googleads_config.yaml for this to work?

line 278, in load_from_storage    config_data = config.load_from_yaml_file(path)
  File "C:\config.py", line 69, in validation_wrapper  config_dict = func(*args, **kwargs)
  File "C:\config.py", line 87, in parser_wrapper  config_dict = func(*args, **kwargs)
  File "C:\config.py", line 274, in load_from_yaml_file  return parse_yaml_document_to_dict(yaml_doc)
  File "C:\config.py", line 70, in validation_wrapper   validate_dict(config_dict)
  File "C:\config.py", line 174, in validate_dict     raise ValueError(
ValueError: The client library configuration is missing the required "use_proto_plus" key. Please set this option to either "True" or "False". For more information about this option see the Protobuf Messages guide: https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages

**Comment by mohabfekry** [comment]
Thanks for raising this! I opened https://github.com/google/customer-match-upload-script/pull/3 accordingly.
